Wireframe task
CodeYourFuture/Module-User-Focused-Data pull request #150
Opened 2024-10-07 19:55 UTC by elmirashafiei

## Learners, PR Template

Self checklist

- [x] I have committed my files one by one, on purpose, and for a reason
- [x] I have titled my PR with COHORT_NAME | FIRST_NAME LAST_NAME | REPO_NAME | WEEK 
- [x] I have tested my changes
- [x] My changes follow the [style guide](https://syllabus.codeyourfuture.io/guides/code-style-guide/)
- [x] My changes meet the [requirements](./README.md) of this task

## Changelist

Briefly explain your PR.

## Questions

Ask any questions you have for your reviewer.

2024-10-07 19:59 UTC, elmirashafiei commented
Please review it.

2024-10-09 08:11 UTC, eediallo commented on Wireframe/styles.css
> +a:hover {
You web page is not only for mouse users: 

```suggestion
//Suggested code change
a:hover, a:focus{
text-decoration: underline;
}

2024-10-09 09:48 UTC, eediallo commented on Wireframe/index.html
>      <meta charset="UTF-8">
Please add the doctype  tag: 
```suggestion
<!DOCTYPE html>
<html lang="en">
<head>
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Wireframe</title>
    <link rel="stylesheet" href="style.css">
    <link rel="stylesheet" href="styles.css">
</head>
<body>
   <-- Body elements go here -->
</body>
</html>
```

Here is why it is important: https://www.geeksforgeeks.org/explain-the-importance-of-doctype-in-html/

2024-10-09 09:58 UTC, eediallo requested changes
Hi @elmirashafiei ! 

Congratulations on successfully submitting your first pull request (PR)! This marks an important milestone in your development journey. 

You can find a preview of your work here: https://deploy-preview-150--cyf-ufd.netlify.app/wireframe/  . Don't you think it would be a good idea to adjust it so that it matches the wireframe given in this task? 

I also recommend incorporating more frequent commits in your workflow, as this will enhance the tracking of your changes and make the process more efficient.

Note that I am also a learner trying to learn how to make code review.

2024-10-09 11:51 UTC, elmirashafiei commented
@eediallo Thanks a lot.
You mentioned important parts.
Thanks again for taking your time and reviewing my codes.

2024-10-09 22:11 UTC, ShayanMahnam commented
please title your pull request correctly following COHORT_NAME | FIRST_NAME LAST_NAME | REPO_NAME | WEEK

2025-01-23 07:24 UTC, closed without merging