Feature/wireframe
CodeYourFuture/Module-User-Focused-Data pull request #164
Opened 2024-10-08 14:54 UTC by AFatmaa

## Learners, PR Template

Self checklist

- [ ] I have committed my files one by one, on purpose, and for a reason
- [ ] I have titled my PR with COHORT_NAME | FIRST_NAME LAST_NAME | REPO_NAME | WEEK 
- [ ] I have tested my changes
- [ ] My changes follow the [style guide](https://syllabus.codeyourfuture.io/guides/code-style-guide/)
- [ ] My changes meet the [requirements](./README.md) of this task

## Changelist

- Used semantic HTML tags to structure the webpage
- Created a page header with a title and description
- Created an articles section with three articles, each including a title, summary, and a link
- Created a page footer and fix it to the bottom of the viewport
- Used the :first-child pseudo-class to style the first article so that it stands out from the others
- Used version control by committing often and pushing regularly to GitHub

## Questions

Ask any questions you have for your reviewer.

2024-10-09 21:39 UTC, ShayanMahnam commented
Welcome to ITP! Congratulations on your first Pull Request! 🎉

It's a wonderful start, @AFatmaa  ! You can see your work deployed on a PR preview here

https://deploy-preview-164--cyf-ufd.netlify.app/my-wireframe/

2024-10-09 21:54 UTC, AFatmaa commented
Hi Shayan,

I changed the title. I will also add images on my articles. 

Thank you!

2024-10-09 22:06 UTC, ShayanMahnam requested changes

2024-10-09 22:06 UTC, ShayanMahnam commented on Wireframe/css/style.css
> +body {
You have both `padding: 0` and `padding-bottom: 50px` set in the body. The general `padding: 0` will override the specific `padding-bottom`.

2024-10-09 22:06 UTC, ShayanMahnam commented on Wireframe/css/style.css
> +  .articles a {
To enhance the user experience, add hover and focus styles to the links. This will make them more interactive

2024-10-10 13:54 UTC, AFatmaa commented
Hi Shayan,
I changed everything you told me. Could you please check if it's correct?
Thank you!

2024-10-16 16:45 UTC, ShayanMahnam commented
well done! It looks neater now 🎉

2024-10-16 21:56 UTC, AFatmaa commented
Thank you, Shayan! 🤗

2025-01-23 07:24 UTC, closed without merging