Cape Town | Serna Malala | Module-User-Focused-Data | Week 1
CodeYourFuture/Module-User-Focused-Data pull request #169
Opened 2024-10-08 19:24 UTC by sernamalala

## Learners, PR Template

Self checklist

- [ ] I have committed my files one by one, on purpose, and for a reason
- [ ] I have titled my PR with COHORT_NAME | FIRST_NAME LAST_NAME | REPO_NAME | WEEK 
- [ ] I have tested my changes
- [ ] My changes follow the [style guide](https://syllabus.codeyourfuture.io/guides/code-style-guide/)
- [ ] My changes meet the [requirements](./README.md) of this task

## Changelist

I have create the Git web page according to the requirements given. There is an HTML and CSS file in the project that I worked on. I am nor 100% sure if I used the :firstchild CSS property correctly but I did use it. 
I am requesting for a review of my work.

## Questions

Are commits required to be regular, I often commit after a bit of time, or should I get into the habit of saving regularly?

2024-10-08 23:23 UTC, islam95 commented
Hi @sernamalala Well done for making the first PR!
You understood the task very well, good job!

Let's try to improve it a little. Have you checked your page at https://validator.w3.org ? Have a look what it suggests. 
I would suggest you to look into the way your wrote anchor tags `<a>` inside `<button>`. Why do you think it's not a best approach to make a button?

2024-10-10 19:46 UTC, islam95 requested changes
Well done! Here I have other suggestions:
- Comparing Wireframe provided and [your page](https://deploy-preview-169--cyf-ufd.netlify.app/wireframe/), last 2 articles a not on the same row. How would you make them look like in the Wireframe picture?
- Footer should be fixed to the bottom of the page. How would make sure it's fixed?

2024-10-10 19:48 UTC, islam95 commented on Wireframe/index.html
> +      To learn more about Git from a pro contact Serna Malala @ sm.sernamalala@gmail.com
There is a nice touch to the emails in html. You basically wrap your email into anchor tag with mailto link. Have a look and try to implement it if you like.
https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_link_mailto

2024-10-27 20:25 UTC, sernamalala commented
Hi @islam95. I added the changes that you suggested since I learned them in the following weeks. Could you please review and add a complete label for this work. Thank you

2024-10-29 21:36 UTC, islam95 commented
Well done @sernamalala Nice touch with the email!

I see you aligned last 2 articles but they are all in one column. Have a look at the wireframe picture from the task and try to put last 2 articles on the same row, so your page looks like a Wireframe provided. You can apply flexbox to a wrapper class for the last 2 articles, which is `#second-part` in your case.

2025-01-23 07:24 UTC, closed without merging