Feature/wireframe
CodeYourFuture/Module-User-Focused-Data pull request #180
Opened 2024-10-10 19:13 UTC by leiliheidarishizari

## Learners, PR Template

Self checklist

- [ ] I have committed my files one by one, on purpose, and for a reason
- [ ] I have titled my PR with COHORT_NAME | FIRST_NAME LAST_NAME | REPO_NAME | WEEK 
- [ ] I have tested my changes
- [ ] My changes follow the [style guide](https://syllabus.codeyourfuture.io/guides/code-style-guide/)
- [ ] My changes meet the [requirements](./README.md) of this task

## Changelist

Briefly explain your PR.

## Questions

Ask any questions you have for your reviewer.

2024-10-10 19:13 UTC, leiliheidarishizari commented
The most upt to date PR

2024-10-12 19:08 UTC, leiliheidarishizari commented
Hi lovely viewers. Your insight of my PR would be highly appreciated. Thanks in advance.

2024-10-13 08:16 UTC, SallyMcGrath commented
> Hi lovely viewers. Your insight of my PR would be highly appreciated. Thanks in advance.

Hi @leiliheidarishizari ! Thanks so much for this. Good start! Look over your PR: does the title match the format asked for? Have you completed all the actions in the task list? Are there questions for your reviewer? 

Take a look at https://github.com/CodeYourFuture/Module-User-Focused-Data/pulls to see how others are doing this.  Let us know when you've updated this PR to meet those requirements. 🙏

2024-10-14 13:15 UTC, leiliheidarishizari commented
> > Hi lovely viewers. Your insight of my PR would be highly appreciated. Thanks in advance.
> 
> Hi @leiliheidarishizari ! Thanks so much for this. Good start! Look over your PR: does the title match the format asked for? Have you completed all the actions in the task list? Are there questions for your reviewer?
> 
> Take a look at https://github.com/CodeYourFuture/Module-User-Focused-Data/pulls to see how others are doing this. Let us know when you've updated this PR to meet those requirements. 🙏

2024-10-14 13:19 UTC, leiliheidarishizari commented
Hi Sally, thank you so much for your comments. I believe that I made a very basic mistakes which is very embarrassing. It was my first project so I was not very familiar with the requirement structures. From now on, I would do all the requirements accordingly :)

2024-10-14 17:12 UTC, SallyMcGrath commented
> Hi Sally, thank you so much for your comments. I believe that I made a very basic mistakes which is very embarrassing. It was my first project so I was not very familiar with the requirement structures. From now on, I would do all the requirements accordingly :)

Definitely working on requirements is important - and something we can all always improve. But oh, if you get embarrassed every time you get help and improvements in code review you'll absolutely _perish_ under the weight of it! Code review isn't about being judged, it's about being helped. 🫶  Developers work in teams and we all help each other.

Look at this - here someone is helping me by code reviewing the curriculum https://github.com/CodeYourFuture/curriculum/pull/188 . 36 comments... maybe that seems a lot but if you look https://github.com/CodeYourFuture/curriculum/pulls?q=is%3Apr+is%3Aclosed+sort%3Acomments-desc there are PRs with over 100 comments! 

Here's people building React over on facebook. [212 comments ](https://github.com/facebook/react/pull/20463)on just one PR! ⛰️ 😉

2024-10-15 06:34 UTC, leiliheidarishizari commented
Hi dear Sally, I've changed everything that you asked accordingly. I also checked the lighthouse which at first was low because of the large size of the images, then I resized them and checked the light house again, all of them are 100% apart from the CEO.I have to check the reasons for that as well. Thanks again for reviewing my PR.

2024-10-19 15:29 UTC, SallyMcGrath requested changes
Hi @leiliheidarishizari .Thanks for this! 🎉 

Your work is deployed here https://deploy-preview-180--cyf-ufd.netlify.app/wireframe/

When I ran lighthouse it told me you had an error. Your touch targets are too small. Run the test and click the links to understand how to fix this. All the help is right there in Devtools. Good luck!

2024-10-20 07:43 UTC, leiliheidarishizari commented
Hi dear Sally. Thanks for you comment. I couldn't find touch targets in my dev tools. I searched about it and I found out ,this error looks like this "Tap targets are not appropriately sized"!!! But I can not find this error!

2024-10-20 10:28 UTC, SallyMcGrath commented
> Hi dear Sally. Thanks for you comment. I couldn't find touch targets in my dev tools. I searched about it and I found out ,this error looks like this "Tap targets are not appropriately sized"!!! But I can not find this error!
<img width="647" alt="Screenshot 2024-10-19 at 16 27 55" src="https://github.com/user-attachments/assets/1aaa1c8a-c8f9-497c-8ed5-1b973512a41d">


Touch targets and tap targets are the same thing. Run the test and click the links on the report -- it will show you what to do.

2024-10-21 02:53 UTC, leiliheidarishizari commented
Hi dear Sally. Thanks for sending the image. It is so clear now however when I check the lighthouse, the accessibility show 100 .I'm wondering why you see 93 with the Touch Target issue. Please kindly find the below screenshot as a proof. Many thanks.
![Screenshot 2024-10-21 034634](https://github.com/user-attachments/assets/8ccc5791-b8ee-40ef-a29d-42178c7656a5)

2024-10-21 09:05 UTC, SallyMcGrath commented
> Hi dear Sally. Thanks for sending the image. It is so clear now however when I check the lighthouse, the accessibility show 100 .I'm wondering why you see 93 with the Touch Target issue. Please kindly find the below screenshot as a proof. Many thanks.
> 
> ![Screenshot 2024-10-21 034634](https://private-user-images.githubusercontent.com/133997325/378257477-8ccebaad-94d6-4942-8fce-2ae0b00c6a5a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1MDE2MzQsIm5iZiI6MTcyOTUwMTMzNCwicGF0aCI6Ii8xMzM5OTczMjUvMzc4MjU3NDc3LThjY2ViYWFkLTk0ZDYtNDk0Mi04ZmNlLTJhZTBiMDBjNmE1YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyMVQwOTAyMTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MzljZjA4YzIyMzhhOTBjYjU5YTZkZGJiOTIyMTgzMmRhMTZkNzk1NDE0OTdiOWEwNWIxZjhjMjIyM2ZlNTA0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.QS8dJVFNSPm_lIv4qmtAANs6gHQ1WDuPldcZFe4MYiE)

Hmm, probably the settings on our respective Lighthouses. Try changing them around -- switch from mobile to desktop, as this is a desktop layout.

2024-10-22 06:07 UTC, leiliheidarishizari commented
Hi dear Sally, I completed your request and the problem has been solved now. Woohoo ;)

2025-01-23 07:24 UTC, closed without merging