Glasgow | Denis Suvorov | Form Controls | Week2
CodeYourFuture/Module-User-Focused-Data pull request #183
Opened 2024-10-10 19:51 UTC by DenS116

<!--

You must title your PR like this:

COHORT_NAME | FIRST_NAME LAST_NAME | REPO_NAME | WEEK

For example,

NW4 | Carol Owen | HTML-CSS-Module | Week1

## Learners, PR Template

Self checklist

- [x] I have committed my files one by one, on purpose, and for a reason
- [x] I have titled my PR with COHORT_NAME | FIRST_NAME LAST_NAME | REPO_NAME | WEEK 
- [x] I have tested my changes
- [x] My changes follow the [style guide](https://syllabus.codeyourfuture.io/guides/code-style-guide/)
- [x] My changes meet the [requirements](./README.md) of this task

2024-10-13 15:46 UTC, SallyMcGrath reviewed
Hi there @DenS116 . When you ran Lighthouse on this code, what did it tell you?

Try running it again and making the changes, like we did in class.

2024-10-13 16:08 UTC, DenS116 commented
> Всем привет@DenS116. Когда вы запустили Lighthouse для этого кода, что он вам сказал?
> 
> Попробуйте запустить его еще раз и внести изменения, как мы это делали на занятии.

Hi Sally, thankyou for your message and review my code. A
<img width="1680" alt="s" src="https://github.com/user-attachments/assets/1b83bbb4-d7d2-4e51-87b4-cbc2735cae30">
ccording to the requirements accessibility score should be 100 in lighthouse. I ran Lighthouse and my code meets the requirements

2024-10-18 16:53 UTC, SallyMcGrath requested changes
Great start @DenS116 . Take a look into what I'm saying about form elements. There's a good tutorial here https://webaim.org/techniques/forms/controls that might help

2024-10-18 16:53 UTC, SallyMcGrath commented on Form-Controls/index.html
> +          <p>Last Name:</p>
```suggestion
          <label for="last_name">Last Name:</label>
```

The label is labelling the input. In devtools, open the Accessibility tree and add some text to your empty label. Can you see the difference?



https://developer.chrome.com/docs/devtools/accessibility/reference#explore-tree

2024-10-18 16:53 UTC, SallyMcGrath commented on Form-Controls/index.html
> +        <div class="shop shop_radio">
Instead of a div, is there a semantic HTML element you could use to group a set of fields?

2024-10-19 11:33 UTC, DenS116 commented
Hi @SallyMcGrath, I really appreciate for your feedback it really helped me to understand the "form" tag more deeply. I studied it in more detail and corrected the recommendations you gave me. I filled the "label" tag instead of 'p' and I changed the "div" tag to the "fieldset" tag which it is schematically more suitable for the form. I will be glad to hear recommendations, thanks

2025-01-23 07:24 UTC, closed without merging