CYF-London| Zohreh Kazemianpour| Module-User-Focused-Data| Week2
CodeYourFuture/Module-User-Focused-Data pull request #212
Opened 2024-10-14 07:56 UTC by zohrehKazemianpour

## Learners, PR Template

Self checklist

- [ ] I have committed my files one by one, on purpose, and for a reason
- [ ] I have titled my PR with COHORT_NAME | FIRST_NAME LAST_NAME | REPO_NAME | WEEK 
- [ ] I have tested my changes
- [ ] My changes follow the [style guide](https://syllabus.codeyourfuture.io/guides/code-style-guide/)
- [ ] My changes meet the [requirements](./README.md) of this task

## Changelist

-Added an HTML form to collect customer names, emails, t-shirt sizes, and colour preferences.
-Added client-side validation for required fields (name, email, and size).
-Enhanced user experience with hover effects on the submit button.

## Questions

Is the way I structured the form layout and used CSS for styling clear and maintainable?

2024-10-18 17:02 UTC, SallyMcGrath requested changes
Thanks for thie @zohrehKazemianpour 

When I ran Lighthouse I found this error. Can you fix it up please? Run Lighthouse before you submit your PR. (If you don't know how to fix it, come to class and ask!) 🫶 

<img width="654" alt="Screenshot 2024-10-18 at 17 58 42" src="https://github.com/user-attachments/assets/556daa97-3b0e-41b7-b26b-9f30703cc990">

2024-10-18 17:02 UTC, SallyMcGrath commented on Form-Controls/index.html
> +      <input type="text" name="name" id="name" required minlength="2" pattern="[A-Za-z\s]+" title="Name must be at least 2 characters and can only contain letters and spaces.">
Interesting! What would happen if they were called O'Donnell?

(This criteria is set just so you can think about this: https://www.kalzumeus.com/2010/06/17/falsehoods-programmers-believe-about-names/)

2024-10-19 08:25 UTC, zohrehKazemianpour commented
@SallyMcGrath Thanks for the feedback I really appreciated it. I have addressed the accessibility issue by adjusting the heading in the footer section. Regarding the pattern attribute for the name field, would you recommend removing the character validation to make it more inclusive? Alternatively, I can modify the pattern attribute to allow letters, spaces, apostrophes, and hyphens (e.g., pattern="[A-Za-z\s'-]+").

2024-10-22 22:18 UTC, cjyuan commented
Form looks good!

"What characters are allowed in a name" is a question developers have to considered. There is no simple answer.

2024-10-23 17:33 UTC, zohrehKazemianpour commented
@cjyuan Thank you for taking the time to review my project and for your valuable feedback.

2025-01-23 07:24 UTC, closed without merging