WestMidlands | Danial Bashirzadeh | Module-User-Focused-Data:Form-Controls | WEEK 2
CodeYourFuture/Module-User-Focused-Data pull request #213
Opened 2024-10-14 11:22 UTC by bashirzadehdanial

## Learners, PR Template

Self checklist

- [ ] I have committed my files one by one, on purpose, and for a reason
- [ ] I have titled my PR with COHORT_NAME | FIRST_NAME LAST_NAME | REPO_NAME | WEEK 
- [ ] I have tested my changes
- [ ] My changes follow the [style guide](https://syllabus.codeyourfuture.io/guides/code-style-guide/)
- [ ] My changes meet the [requirements](./README.md) of this task

## Changelist

Briefly explain your PR.

## Questions

Ask any questions you have for your reviewer.

2024-10-18 16:57 UTC, SallyMcGrath requested changes
It's a good start @bashirzadehdanial ! Thanks for this. When I ran Lighthouse I got an error that needs fixing. Take a look please!

Always run Lighthouse before you submit.
<img width="618" alt="Screenshot 2024-10-18 at 17 55 44" src="https://github.com/user-attachments/assets/16f7ee12-007e-481a-9754-08c7c2ae9ef1">

2024-10-18 18:43 UTC, bashirzadehdanial commented
Hi @SallyMcGrath, Thank you for your code review and for pointing out the Lighthouse issues. I’ve resolved the color contrast issues identified by Lighthouse. Please see the attached screenshot for confirmation.

Thanks!

2024-10-18 18:44 UTC, bashirzadehdanial commented
<img width="1790" alt="Screenshot 2024-10-18 at 19 30 07" src="https://github.com/user-attachments/assets/41690bc7-72bc-4fbf-87f0-c03dbd3fedfa">

2024-10-24 20:52 UTC, bashirzadehdanial commented
Hi @SallyMcGrath,

I've updated the code based on your feedback. Could you please review, approve, and add the "complete" label to the pull request when you have a chance?

Thanks in advance!

2025-01-23 07:24 UTC, closed without merging