London | Ameneh Keshavarzmohamadian | Form Controls | Week 2
CodeYourFuture/Module-User-Focused-Data pull request #216
Opened 2024-10-14 14:33 UTC by Ameneh-Keshavarz

## Learners, PR Template

Self checklist

- [ ] I have committed my files one by one, on purpose, and for a reason
- [ ] I have titled my PR with COHORT_NAME | FIRST_NAME LAST_NAME | REPO_NAME | WEEK 
- [ ] I have tested my changes
- [ ] My changes follow the [style guide](https://syllabus.codeyourfuture.io/guides/code-style-guide/)
- [ ] My changes meet the [requirements](./README.md) of this task

## Changelist

Briefly explain your PR.

## Questions

Ask any questions you have for your reviewer.

2024-10-14 22:03 UTC, islam95 requested changes
Hi @Ameneh-Keshavarz. Good job.

Here are some of my suggestions for you to address. Please, let me know if you need any help. Thanks.

2024-10-19 22:21 UTC, islam95 commented on Form-Controls/index.html
> +    <input type="date" id="delivery-date" name="delivery-date" required>
Date should be from a constrained date range. so don't remove min and max, rather add dates in them.

2024-10-20 15:29 UTC, Ameneh-Keshavarz commented on Wireframe/index.html
> +</html>
Thanks, I tried to fix this by using 'git checkout main Wireframe' to retrieve the Wireframe from the main branch. However, I'm not sure what is the best approach to fix this.

2024-10-20 15:32 UTC, Ameneh-Keshavarz commented on Form-Controls/index.html
> +    <input type="text" id="name" name="name" required minlength="2" pattern="[A-Za-z\s]+" placeholder="Your Name">
Thanks, I removed the pattern attribute to make the name input more inclusive.

2024-10-21 18:58 UTC, islam95 commented
@Ameneh-Keshavarz everything looks good. You just need to fix min and max for delivery date.

2024-10-29 21:38 UTC, islam95 commented
Good job

2025-01-23 07:23 UTC, closed without merging