GlasgowClass/ShreefAhmed/Form-controls/week2
CodeYourFuture/Module-User-Focused-Data pull request #244
Opened 2024-10-18 12:07 UTC by shreefAhmedM

## Learners, PR Template

Self checklist

- [ ] I have committed my files one by one, on purpose, and for a reason
- [ ] I have titled my PR with COHORT_NAME | FIRST_NAME LAST_NAME | REPO_NAME | WEEK 
- [ ] I have tested my changes
- [ ] My changes follow the [style guide](https://syllabus.codeyourfuture.io/guides/code-style-guide/)
- [ ] My changes meet the [requirements](./README.md) of this task

## Changelist

Briefly explain your PR.

## Questions

Ask any questions you have for your reviewer.

2024-10-26 09:03 UTC, jamesbaskerville requested changes
Good start on the form! Would be great to see some styling for visual purposes and to meet the CSS requirements ("I show which element is focused.")

2024-10-26 09:03 UTC, jamesbaskerville commented on Form-Controls/index.html
> +      <input type="text" placeholder="full Name" required />
What requirements do we have for validating the name?

2024-10-26 09:03 UTC, jamesbaskerville commented on Form-Controls/index.html
> +     <label for="date">Choos delivery date:</label>
nit: typo!

2024-10-26 09:03 UTC, jamesbaskerville commented on Form-Controls/index.html
> +    <input type="date" id="date" name="date" main="2024-10-16" max="2024-11-16" required>
I seem to be able to select a date in September -- why might your constraints not be applying correctly?

2024-10-26 09:04 UTC, jamesbaskerville commented
Also @shreefAhmedM you can take this PR out of draft mode -- Draft usually indicates that the PR is not yet ready for review

2024-11-20 11:42 UTC, SallyMcGrath commented
@shreefAhmedM , you need to make changes in response to comments. This is how code review works. It's how seniors support you to improve. (In tech, we help each other with our homework!) 

I am approving your step submission. For _your own learning_, you must take the opportunity to revise your work in response to feedback. This is not about getting a grade, but about developing yourself to be competitive on the job market as a junior dev. It's incredibly competitive nowadays and coasting/ box-ticking won't work.

2025-01-23 07:24 UTC, closed without merging