LONDON | DANIEL ALEXANDER | FORM CONTROLS | WEEK 2
CodeYourFuture/Module-User-Focused-Data pull request #276
Opened 2024-10-21 21:55 UTC by Daniel-Alexander-The-Great

## Learners, PR Template

Self checklist

- [ ] I have committed my files one by one, on purpose, and for a reason
- [ ] I have titled my PR with COHORT_NAME | FIRST_NAME LAST_NAME | REPO_NAME | WEEK 
- [ ] I have tested my changes
- [ ] My changes follow the [style guide](https://syllabus.codeyourfuture.io/guides/code-style-guide/)
- [ ] My changes meet the [requirements](./README.md) of this task

## Changelist

Written up HTML and CSS for basic form.

## Questions

Would like to have a rolling date feature where the min date in calendar is always day of accessing website but it seems this is a JS feature?

2024-10-26 17:31 UTC, mrvicthor requested changes
Hi @Daniel-Alexander-The-Great, brilliant work here with the form.
I have left a few comments for you to address.

2024-10-26 17:31 UTC, mrvicthor commented on Form-Controls/index.html
Hi @Daniel-Alexander-The-Great,
Brilliant work here.
Just a nitpick. How about replacing the name property of the input field for Name with _username_? I think it is easier to read.

`<div>
     <label for="username">Name: <span aria-label="required">*</span></label>
        <input id="name" type="text" name="username" required />
 </div>
`

2024-10-26 17:31 UTC, mrvicthor commented on Form-Controls/index.html
> +    <h2>By Daniel Alexander</h2>
Hi @Daniel-Alexander-The-Great,
Any specific reason for using a h2 element here?

2024-10-26 17:31 UTC, mrvicthor commented on Form-Controls/styles.css
> +    margin: 10px;
Hi @Daniel-Alexander-The-Great ,
I will suggest using rem except if you want the element to have a fixed size e.g (border, and box-shadow).

2024-10-26 17:31 UTC, mrvicthor commented on Form-Controls/styles.css
> +    margin: 10px;
Hi @Daniel-Alexander-The-Great 
Same as previous comment.

2024-10-26 17:31 UTC, mrvicthor commented on Form-Controls/styles.css
> +    padding: 5px 10px;
Hi @Daniel-Alexander-The-Great,
Same as previous comment.

2024-10-26 17:31 UTC, mrvicthor commented on Form-Controls/styles.css
> +    margin: 5px;
Hi @Daniel-Alexander-The-Great ,
Same as previous comment.

2024-10-27 08:09 UTC, SallyMcGrath commented on Form-Controls/index.html
Hmm, the form requirements don't ask for a username. They ask for a name. I think there is a difference. What do you think?

https://design-system.service.gov.uk/patterns/names/

2024-10-27 12:51 UTC, mrvicthor commented on Form-Controls/index.html
Hi @SallyMcGrath , thanks for your feedback. I thought it would help differentiate between the name attribute and the name. However, I am happy to mark this as resolved.

2025-01-23 07:23 UTC, closed without merging