CYF London | Rihanna Poursoltani | Module User Focused Data | Form controls | Week 2
CodeYourFuture/Module-User-Focused-Data pull request #279
Opened 2024-10-22 09:06 UTC by RihannaP

## Learners, PR Template

Self checklist

- [ ] I have committed my files one by one, on purpose, and for a reason
- [ ] I have titled my PR with COHORT_NAME | FIRST_NAME LAST_NAME | REPO_NAME | WEEK 
- [ ] I have tested my changes
- [ ] My changes follow the [style guide](https://syllabus.codeyourfuture.io/guides/code-style-guide/)
- [ ] My changes meet the [requirements](./README.md) of this task

## Changelist

- Added valid inputs with associated labels for name, email, radio, date and select.All of inputs are required.
- My Lighthouse Accessibility score (for Desktop and Mobile)  is 100.
- Added 6 options for size with select and 3 options for colours with using fieldset and radio inputs.
- Adde two buttons for submit and reset.
- Added style, hover and focus for labels, inputs and buttons.

## Questions

- I had problem for setting size for select option. As you can see width is not the same as others in the page.How can I fix that?

Ask any questions you have for your reviewer.

2024-10-25 16:38 UTC, mrvicthor commented on Form-Controls/styles.css
> +    font-size: 15px;
Hi @RihannaP ,
Are you using px for the font-size because you want it to be fixed? Have you considered the benefits of using rem over px?

2024-10-25 16:38 UTC, mrvicthor commented on Form-Controls/styles.css
> +    max-width: 600px;
Hi @RihannaP ,
Same as previous comment.

2024-10-25 16:40 UTC, mrvicthor requested changes
Hi @RihannaP , excellent use form attributes.
However, I have a left a few comments for you to consider.

2024-10-26 10:03 UTC, RihannaP commented
@mrvicthor Thank you so much for your review. I fixed that.

2024-10-26 10:44 UTC, mrvicthor approved these changes
Hi @RihannaP ,
Looks good to me. Happy to approve.

2024-10-29 19:25 UTC, mrvicthor approved these changes
Hi @RihannaP ,
Brilliant work here. Happy to approve.

2025-01-23 07:23 UTC, closed without merging