LONDON 11 | LOVETH OKAFOR | MODULE-USER-FOCUSED-DATA  | SPRINT 2
CodeYourFuture/Module-User-Focused-Data pull request #286
Opened 2024-10-26 11:07 UTC by loveth900

## Learners, PR Template

Self checklist

- [X]  I have committed my files one by one, on purpose, and for a reason
- [X]  I have titled my PR with COHORT_NAME | FIRST_NAME LAST_NAME | REPO_NAME | WEEK 
- [X]  I have tested my changes
- [X]   My changes follow the [style guide](https://syllabus.codeyourfuture.io/guides/code-style-guide/)
- [X]  My changes meet the [requirements](./README.md) of this task

## Changelist

well i learn a lot in this form excerise styling up the work making changes which seems initially as a huge task but i came through.

## Questions

Ask any questions you have for your reviewer.

2024-11-02 16:01 UTC, SallyMcGrath requested changes
Thanks for this @loveth900 ! It looks like there are quite a few criteria not yet met. 

Run Lighthouse and make your changes. Validate your HTML. Carefully check off each criteria in the readme and make sure you really are meeting them all. Comment back if you need help with any of this, or bring your work to study group in class.  Good luck!

2024-11-09 12:11 UTC, loveth900 commented on Form-Controls/index.html
> +  <body>
I remove the extra body tag. I don't need two body tags, only one is needed.

2024-11-09 12:12 UTC, loveth900 commented on Form-Controls/index.html
> +      <form action="submit-order" method="POST">
I realise `action` is not needed at this stage. I am not testing it yet for the server side.

2024-11-09 12:16 UTC, loveth900 commented on Form-Controls/index.html
> +          <input type="text" id="name" name="name" placeholder="Enter your name" required>
I added the validation to the name

2024-11-09 12:52 UTC, loveth900 commented on Form-Controls/index.html
> +          <input type="datetime-local" id="deliveryTime" name="deliveryTime" required>
For the time, I add min and max.

2024-11-09 12:55 UTC, loveth900 commented on Form-Controls/styles.css
> +    padding-bottom: 10px;
i change i to shorthand.

2024-11-09 13:01 UTC, loveth900 commented on Form-Controls/styles.css
> +  .form-group button:hover {
Thanks @SallyMcGrath I can use the "focus" psuedo class for keyboard user and I updated it.

2024-11-09 13:06 UTC, loveth900 commented
@SallyMcGrath  Could you please check my commits.

2025-01-23 07:23 UTC, closed without merging