lon| Amirhossein Aminian| Module-User-Focused-Data| week1
CodeYourFuture/Module-User-Focused-Data pull request #290
Opened 2024-10-26 14:55 UTC by Amir200524

## Learners, PR Template

Self checklist

- [x] I have committed my files one by one, on purpose, and for a reason
- [x] I have titled my PR with COHORT_NAME | FIRST_NAME LAST_NAME | REPO_NAME | WEEK 
- [x] I have tested my changes
- [x] My changes follow the [style guide](https://syllabus.codeyourfuture.io/guides/code-style-guide/)
- [x] My changes meet the [requirements](./README.md) of this task

## Changelist

Briefly explain your PR.

## Questions

Ask any questions you have for your reviewer.

2024-10-26 17:59 UTC, Amir200524 commented
Hi @SallyMcGrath. I want to let you know that I had to close my pervious pull request and open new one because I did it on the wrong branch. Also, I did changes as your wish.

2024-10-26 18:22 UTC, mrvicthor requested changes
Hi @Amir200524 ,
Brilliant work here with the article element.

I have left some comments for you to address.

2024-10-26 18:22 UTC, mrvicthor commented on Form-Controls/styles.css
> +    border:20px solid  red ;
Hi @Amir200524 ,
Why use a border of 20px?

2024-10-26 18:22 UTC, mrvicthor commented on Form-Controls/styles.css
> +    padding: 50px 50px;
Hi @Amir200524 ,
Is there a reason for using px? I think px should only be used for elements with fixed size (e.g border, and box-shadow). I think rem is a better option.

For more context, below is a link 

https://www.shecodes.io/athena/28078-when-to-use-ems-rems-and-px-in-css

2024-10-26 18:22 UTC, mrvicthor commented on Form-Controls/styles.css
> +    margin-top: 40px;
Hi @Amir200524 ,
See previous comment about px.

2024-10-26 18:22 UTC, mrvicthor commented on Form-Controls/styles.css
> +    margin-bottom: 20px;
Hi @Amir200524 ,
Same as previous comment.

2024-10-26 18:22 UTC, mrvicthor commented on Form-Controls/styles.css
> +    margin-bottom: 20px;
Hi @Amir200524 ,
Same as previous comment.

2024-10-26 18:22 UTC, mrvicthor commented on Form-Controls/styles.css
> +    margin-bottom: 20px;
Hi @Amir200524 ,
Same as previous comment.

2024-10-26 18:22 UTC, mrvicthor commented on Wireframe/css/style.css
> +    padding: 20px 0;
Hi @Amir200524 ,
Same as previous comment about px.

2024-10-26 18:22 UTC, mrvicthor commented on Wireframe/css/style.css
> +    margin: 5px 0;
Hi @Amir200524 ,
Same as previous comment.

2024-10-26 18:22 UTC, mrvicthor commented on Wireframe/css/style.css
> +    padding: 20px;
Hi @Amir200524 ,
Same as previous comment.

2024-10-26 18:22 UTC, mrvicthor commented on Wireframe/css/style.css
> +    margin: 20px 150px;
Hi @Amir200524 ,
Same as previous comment.

2024-10-26 18:22 UTC, mrvicthor commented on Wireframe/css/style.css
> +    padding: 15px;
Hi @Amir200524 ,
Same as previous comment.

2024-10-26 18:22 UTC, mrvicthor commented on Wireframe/css/style.css
> +    margin: 35px 20px 40px;
Hi @Amir200524 ,
Same as previous comment.

2024-10-26 18:22 UTC, mrvicthor commented on Wireframe/css/style.css
> +    padding: 10px 0;
Hi @Amir200524 ,
Same as previous comment.

2024-10-26 18:22 UTC, mrvicthor commented on Wireframe/style.css
> +    padding: 20px;
Hi @Amir200524 ,
Same as previous comment about px.

2024-10-26 18:22 UTC, mrvicthor commented on Wireframe/style.css
> +    padding: 20px 0;
Hi @Amir200524 ,
Same as previous comment

2024-10-26 18:22 UTC, mrvicthor commented on Wireframe/style.css
> +    letter-spacing: 2px;
Hi @Amir200524 ,
Same as previous comment.

2024-10-26 18:22 UTC, mrvicthor commented on Wireframe/style.css
> +    margin-top: 10px;
Hi @Amir200524 ,
Same as previous comment.

2024-10-26 18:22 UTC, mrvicthor commented on Wireframe/style.css
> +    padding: 20px;
Hi @Amir200524 ,
Same as previous comment.

2024-10-26 18:22 UTC, mrvicthor commented on Wireframe/style.css
> +    margin-bottom: 15px;
Hi @Amir200524 ,
Same as previous comment.

2024-10-26 18:22 UTC, mrvicthor commented on Wireframe/style.css
> +    margin-bottom: 15px;
Hi @Amir200524 ,
Same as previous comment

2024-10-26 18:22 UTC, mrvicthor commented on Wireframe/style.css
> +    margin-top: 40px;
Hi @Amir200524 ,
Same as previous comment.

2024-10-26 18:22 UTC, mrvicthor commented on Wireframe/style.css
> +    padding: 10px;
Hi @Amir200524 ,
Same as previous comment.

2024-10-27 01:15 UTC, mrvicthor requested changes
Hi @Amir200524 ,
Happy to approve as soon as comments have been resolved.

2024-10-27 01:15 UTC, mrvicthor commented on Wireframe/css/style.css
> +    padding: 30px 30px;
Hi @Amir200524,
I will suggest using rem over px for elements that do not have fixed sizes. 

Please see link below for reference

https://www.shecodes.io/athena/28078-when-to-use-ems-rems-and-px-in-css

2024-10-27 01:15 UTC, mrvicthor commented on Wireframe/css/style.css
> +    margin: 10px 350px;
Hi @Amir200524 ,
Same as previous comment

2024-10-27 01:15 UTC, mrvicthor commented on Wireframe/css/style.css
> +    margin: 35px 200px;
Hi @Amir200524 ,
Same as previous comment.

2024-10-27 01:15 UTC, mrvicthor commented on Wireframe/css/style.css
> +    padding: 35px;
Hi @Amir200524 ,
Same as previous comment.

2024-10-27 01:15 UTC, mrvicthor commented on Wireframe/css/style.css
> +    padding: 30px 0;
Hi @Amir200524 ,
Same as previous comment.

2024-10-27 01:15 UTC, mrvicthor commented on Wireframe/css/style.css
> +    height: 80px;
Hi @Amir200524 ,
Same as previous comment.

2024-10-27 01:15 UTC, mrvicthor commented on Wireframe/index.html
>      <!-- Footer -->
Hi @Amir200524 ,
Is the footer element supposed to be outside of the body tag?

2024-10-27 12:54 UTC, mrvicthor approved these changes
Hi @Amir200524 ,
Looks good to me. Happy to approve.

2025-01-23 07:23 UTC, closed without merging