CYF North West | Yulia I | Module User Focused Data | Week 2
CodeYourFuture/Module-User-Focused-Data pull request #291
Opened 2024-10-26 16:20 UTC by Yulia-I19

Self checklist

✅ I have committed my files one by one, on purpose, and for a reason
✅ I have titled my PR with COHORT_NAME | FIRST_NAME LAST_NAME | REPO_NAME | WEEK 
✅ I have tested my changes
✅ My changes follow the [style guide](https://syllabus.codeyourfuture.io/guides/code-style-guide/)
✅ My changes meet the [requirements](./README.md) of this task

Changelist

I have created a form to collect the customer's data using HTML and CSS. I also tested it using DevTools such as Lighthouse and Device Mode.

Questions

How can I avoid excessive whitespace in my layout, especially in the footer?
Do you have any ideas on how I can make the code better?
I would be grateful for your answers and any suggestions.

2024-10-26 17:47 UTC, mrvicthor requested changes
Hi @Yulia-I19 ,
Excellent work with the form and using form attributes. Almost there.
I have left a few suggestions for you to consider.

2024-10-26 17:47 UTC, mrvicthor commented on Form-Controls/index.html
> +      <input type="text" id="name" name="name" required pattern="[A-Za-z\s]{2,}" title="Please enter at least 2 letters.">
Hi @Yulia-I19 ,
Just a nitpick, how about replacing the name with username for readability. Also, why use _title_ attribute in the input field? I think you meant to use **placeholder**

2024-10-26 17:47 UTC, mrvicthor commented on Form-Controls/index.html
> +      <input type="email" id="email" name="email" required pattern="[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$" title="Please enter a valid email address.">
Hi @Yulia-I19 ,
Any reason for using title attribute in the input element? I think placeholder attribute may be more suitable.

2024-10-26 17:47 UTC, mrvicthor commented on Form-Controls/styles.css
> +    max-width: 400px;
Hi @Yulia-I19 ,
Have you considered the benefits of using rem over px? I think px should be used only for elements with fixed sizes (e.g. border, and box-shadow). I think rem is more suitable. 

See link below for more context.
https://www.shecodes.io/athena/28078-when-to-use-ems-rems-and-px-in-css

2024-10-26 17:47 UTC, mrvicthor commented on Form-Controls/styles.css
> +    padding: 5px;
Hi @Yulia-I19 ,
Same as previous comment.

2024-10-27 11:42 UTC, Yulia-I19 commented
Hi @mrvicthor,
Thank you for your feedback! I’ve made updates to my website based on your suggestions and would be grateful if you could check it out again.

2024-10-27 13:03 UTC, mrvicthor requested changes
Hi @Yulia-I19 ,
Thanks for addressing my earlier comments. 
Just a few more to address and we are done.

2024-10-27 14:38 UTC, Yulia-I19 commented
Hi @mrvicthor,
Thanks for spotting the issues in my code! Now I'll remember when to use px and rem. If you notice anything else, please just let me know.
Thank you.

2025-01-23 07:23 UTC, closed without merging