CYF NORTH WEST| HABEN SOLOMON KIDANE| Module User Focused Data| Form controls| week 2
CodeYourFuture/Module-User-Focused-Data pull request #298
Opened 2024-10-28 19:51 UTC by Habenk-coder

CYF NORTH WEST | HABEN SOLOMON KIDANE | Module User Focused Data| Form Controls | WEEK2

## Learners, PR Template

Self checklist

- [x] I have committed my files one by one, on purpose, and for a reason
- [x] I have titled my PR with COHORT_NAME | FIRST_NAME LAST_NAME | REPO_NAME | WEEK 
- [x] I have tested my changes
- [x] My changes follow the [style guide](https://curriculum.codeyourfuture.io/guides/reviewing/style-guide/)
- [x] My changes meet the [requirements](./README.md) of this task

## Changelist

Briefly explain your PR.

## Questions
Needs Review

2024-10-28 19:57 UTC, Habenk-coder commented
I am looking for your constructive feedbacks

2024-11-02 16:09 UTC, cjyuan commented
- The current branch is created from wireframe branch and not from the main branch. Please try to seek help from volunteers in Saturday workshop to rebase this branch so that it branch out from main.

2024-11-02 16:18 UTC, SallyMcGrath requested changes
Thanks for this @Habenk-coder . There are a few things going on in here for you to look at.

First, please back out your other changes and just open a PR with the changes related to form controls. Next, please review the acceptance criteria and check your submission meets them. It's helpful to write them out one by one as comments in your file to help you check this. 

Make sure to run Lighthouse and follow the advice it gives you to make your changes. Good luck! Come to class to get help if you are stuck.

2024-11-02 16:18 UTC, SallyMcGrath commented on Cakes-Co/index.html
> +          we believe that every celebration deserves a cake that is as unique and special as the occasion itself.
It looks like there are files in this PR that don't belong to this project. Can you open a PR with just the changes for Form Controls, please? Come to class to get help with this if you are stuck.

2024-11-02 16:18 UTC, SallyMcGrath commented on Form-Controls/index.html
> +      <input type="text" id="name" name="name" required minlength="2" pattern="[A-Za-z]+">
What would happen if my name was O'Donnell? 

https://www.kalzumeus.com/2010/06/17/falsehoods-programmers-believe-about-names/

2024-11-02 16:18 UTC, SallyMcGrath commented on Form-Controls/index.html
> +      <div class="error-message">Please enter a valid email address.</div>
What will happen with these error messages? Can you talk through what you expect?

2024-11-02 16:18 UTC, SallyMcGrath commented on Form-Controls/index.html
> +    document.addEventListener("DOMContentLoaded", function() {
Does this meet the criteria listed in the readme? Can you explain how it does, or what your goal in with including this?

2024-11-02 16:18 UTC, SallyMcGrath commented on Form-Controls/styles.css
> +  footer a:hover {
What would happen if I wasn't using a mouse?

2025-01-23 07:23 UTC, closed without merging