ITP | Sami Sardarzai | Module-User-Focused-Data | Week3
CodeYourFuture/Module-User-Focused-Data pull request #302
Opened 2024-10-31 10:01 UTC by samisardarzai

## Learners, PR Template

Self checklist

- [ ] I have committed my files one by one, on purpose, and for a reason
- [ ] I have titled my PR with COHORT_NAME | FIRST_NAME LAST_NAME | REPO_NAME | WEEK 
- [ ] I have tested my changes
- [ ] My changes follow the [style guide](https://curriculum.codeyourfuture.io/guides/reviewing/style-guide/)
- [ ] My changes meet the [requirements](./README.md) of this task

## Changelist

Briefly explain your PR.
Added a new T-Shirt Order form with HTML5 form controls
Implemented input validation for customer name, email, color, size, and delivery date
Styled the form to enhance accessibility and user experience

## Questions

Ask any questions you have for your reviewer.
Could you check if the date validation logic aligns with the requirements?
Any tips for simplifying my CSS for better readability?

2024-11-02 15:05 UTC, cjyuan commented
- What is the lighthouse score you got from Chrome? On mine it is not yet 100.

- If you were asked to specify a constrained date range (says from 1/11/2024 to 28/11/2024) for the preferred delivery date, how would you enforce that with only HTML?

- In terms of simplifying CSS, there doesn't seem much room left to simplify. You can ask ChatGPT and then see if you agree with the suggested change.

Form looks good to me. Personally I prefer the label to be left justified, but I am not qualified to give advice on design.

2024-11-02 19:59 UTC, mrvicthor requested changes
Hi @samisardarzai ,
Excellent work here. 
However, I have left a few comments here for you to address.

2024-11-02 19:59 UTC, mrvicthor commented on Form-Controls/index.html
Hi @samisardarzai ,
Excellent work here with the form.

2024-11-02 19:59 UTC, mrvicthor commented on Form-Controls/styles.css
Hi @samisardarzai ,
Just a nit-pick, apart from the border, and box-shadow (where the size is fixed), I think it is better to use rem as opposed to px.

2024-11-05 12:02 UTC, samisardarzai commented
Hello and thank you for your feedback @cjyuan 

**1. Lighthouse Score:**
I ran the Lighthouse test on my setup, and both mobile and desktop scores are at 100/100. I’ve attached a screenshot to show the results.
<img width="919" alt="Screenshot 2024-11-05 112312" src="https://github.com/user-attachments/assets/40fc7ae0-7c88-48f2-96e7-d1b82c0e237a">

**2. Date Range Constraint:**
To enforce a constrained date range in HTML, I set the min and max attributes on the date input field. This limits the date selection from 1st November 2024 to 28th November 2024, ensuring users can only pick a date within that range.

**3. CSS Simplification:**
After reviewing the CSS, I did simplify it further as much as possible. I combined some of the selectors and minimized the redundancy by grouping shared properties together. The changes mostly involved merging styles for input, select, and button elements, and using shorthand for the box-shadow property. This made the code cleaner without altering the design.

2024-11-05 12:04 UTC, samisardarzai commented on Form-Controls/styles.css
Hello @mrvicthor, thank you for your feedback! I will look into making the changes based on your suggestions as well.

2024-11-05 17:22 UTC, cjyuan commented
Form looks good!

2024-11-05 21:55 UTC, samisardarzai commented
@cjyuan  Thank you !

2025-01-23 07:23 UTC, closed without merging