CYF Glasgow Dalila Boumezrag |  Module-User-Focused-Data | week 2
CodeYourFuture/Module-User-Focused-Data pull request #315
Opened 2024-11-09 11:59 UTC by DalilaBou

## Learners, PR Template

Self checklist

- [ ] I have committed my files one by one, on purpose, and for a reason
- [ ] I have titled my PR with COHORT_NAME | FIRST_NAME LAST_NAME | REPO_NAME | WEEK 
- [ ] I have tested my changes
- [ ] My changes follow the [style guide](https://curriculum.codeyourfuture.io/guides/reviewing/style-guide/)
- [ ] My changes meet the [requirements](./README.md) of this task

## Changelist

Briefly explain your PR.

## Questions

Ask any questions you have for your reviewer.

2024-11-12 13:15 UTC, DalilaBou reviewed
i fix it

2024-11-15 18:15 UTC, fcaroline2020 commented
Hi Dalila has this been reviewed already? It is missing the labels

2024-11-20 12:05 UTC, SallyMcGrath requested changes
Hi @DalilaBou 

You have not added any validation attributes to your form, or a submit button. Please look again at the criteria. Go through each requirement and make sure you have actually met each one.

We really want to validate all data that we accept into a database. Revisit the prep materials, including the Q&A session, and have a proper think about this 

https://programming.codeyourfuture.io/user-data/sprints/2/prep/

2024-11-20 12:05 UTC, SallyMcGrath commented on Form-Controls/index.html
> +    <input type="text" placeholder="Name">
What would happen if the customer did not add a name? What if the name they added was a number?

What do the criteria say about what the code needs to do?

2024-11-20 12:05 UTC, SallyMcGrath commented on Form-Controls/index.html
> +<label for="email"> Your Email</label>
When you tested your form, what happened when you submitted an invalid email? 

What about no email?

2024-11-20 12:05 UTC, SallyMcGrath commented on Form-Controls/index.html
> +
How can the user submit this data?

2024-11-20 12:05 UTC, SallyMcGrath commented on Form-Controls/index.html
>    </header>
What is this doing here? What does main mean?

2024-12-04 14:17 UTC, closed without merging