CYF-London | Birhan Mesfen | Module-User-Focused-Data | Week 2
CodeYourFuture/Module-User-Focused-Data pull request #323
Opened 2024-11-12 16:43 UTC by Birhan-lab

## Learners, PR Template

Self checklist

- [X] I have committed my files one by one, on purpose, and for a reason
- [X] I have titled my PR with COHORT_NAME | FIRST_NAME LAST_NAME | REPO_NAME | WEEK 
- [X] I have tested my changes
- [X] My changes follow the [style guide](https://curriculum.codeyourfuture.io/guides/reviewing/style-guide/)
- [X] My changes meet the [requirements](./README.md) of this task

## Changelist
- This pr is all about building form control for an online shop.

## Questions

Ask any questions you have for your reviewer.

2024-11-15 09:53 UTC, mrvicthor commented on Form-Controls/index.html
Hi @Birhan-lab ,
Great work here with the form. 
For accessibility reasons, I think the value of the for attribute in the label element and the id attribute of the associated input element should be the same. For example.

<label for='address'>Address</label>
<input type='text' id='address' name='address' />

2024-11-15 09:59 UTC, mrvicthor requested changes
Hi @Birhan-lab ,
I have left a few comments for you to address.

2024-11-15 09:59 UTC, mrvicthor commented on Form-Controls/styles.css
Hi @Birhan-lab ,
Excellent work here as well with the styling.
However, it is good practice to use px for elements with fixed sizes (e.g., border, and box-shadow), and rem for other elements. The benefits of using rem over px is that it will adjust automatically to fit the size of the device screen.

2024-12-09 14:17 UTC, Birhan-lab commented on Form-Controls/index.html
This is done ,than you

2024-12-09 14:26 UTC, Birhan-lab commented on Form-Controls/styles.css
resolved ,thank you

2025-01-23 07:23 UTC, closed without merging