CYF Glasgow Dalila Boumezrag | Module-User-Focused-Data | week 2
CodeYourFuture/Module-User-Focused-Data pull request #332
Opened 2024-12-13 16:38 UTC by DalilaBou

<!--

You must title your PR like this:

CYF Glasgow Dalila Boumezrag | Module-User-Focused-Data | week 2

## Learners, PR Template

Self checklist

- [Done  ] I have committed my files one by one, on purpose, and for a reason
- [Done  ] I have titled my PR with COHORT_NAME | FIRST_NAME LAST_NAME | REPO_NAME | WEEK 
- [Done ] I have tested my changes
- [Done ] My changes follow the [style guide](https://curriculum.codeyourfuture.io/guides/reviewing/style-guide/)
- [Done ] My changes meet the [requirements](./README.md) of this task

Ask any questions you have for your reviewer.

2024-12-14 11:11 UTC, mrvicthor commented on Form-Controls/index.html
Hi @DalilaBou, 
Excellent work here with the form

2024-12-14 11:13 UTC, mrvicthor commented on Form-Controls/styles.css
Hi @DalilaBou ,
I think it is better to use px for elements with fixed sizes (e.g border, and box-shadow). Hence, I will recommend using rem instead of px.

2024-12-14 11:16 UTC, mrvicthor requested changes
Hi @DalilaBou ,
Brilliant work here. However, I have left a few comments for you to address. Happy to approve once this is addressed.

Thanks

2024-12-14 11:16 UTC, mrvicthor commented on Wireframe/css/style.css
Hi @DalilaBou ,
See previous comment about using rem instead of px

2024-12-14 11:16 UTC, mrvicthor commented on Wireframe/index.html
Hi @DalilaBou ,
I just observed that the alt attribute in the img element is empty. Was this intentional?

2024-12-16 20:56 UTC, DalilaBou commented on Wireframe/css/style.css
HI @mrvicthor  thanks for your feedback i will go through it

2024-12-16 20:56 UTC, DalilaBou commented on Wireframe/index.html
HI @mrvicthor  thanks for your feedback i will go through it

2025-01-23 07:23 UTC, closed without merging